web/router.ex
defmodule PhoenixCommerce.Router do
  use PhoenixCommerce.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PhoenixCommerce do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/products", ProductController

    get "/cart", CartController, :show

    post "/cart/add", CartController, :add, as: :add_to_cart
  end

  # Other scopes may use custom stacks.
  # scope "/api", PhoenixCommerce do
  #   pipe_through :api
  # end
end

lib/phoenix_commerce/endpoint.ex
defmodule PhoenixCommerce.Endpoint do
  use Phoenix.Endpoint, otp_app: :phoenix_commerce

  socket "/socket", PhoenixCommerce.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :phoenix_commerce, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_phoenix_commerce_key",
    signing_salt: "bLy/nJe8"

  plug PhoenixCommerce.Router
end

lib/phoenix_commerce/repo.ex
defmodule PhoenixCommerce.Repo do
  use Ecto.Repo, otp_app: :phoenix_commerce
end

web/models/cart.ex
defmodule PhoenixCommerce.Cart do
  use PhoenixCommerce.Web, :model

  schema "carts" do
    field :uuid, Ecto.UUID, autogenerate: true
    has_many :line_items, PhoenixCommerce.LineItem
    timestamps
  end

  @required_fields ~w()
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/models/line_item.ex
defmodule PhoenixCommerce.LineItem do
  use PhoenixCommerce.Web, :model

  schema "line_items" do
    field :quantity, :integer
    belongs_to :product, PhoenixCommerce.Product
    belongs_to :cart, PhoenixCommerce.Cart
    timestamps
  end

  @required_fields ~w(product_id quantity cart_id)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/models/product.ex
defmodule PhoenixCommerce.Product do
  use PhoenixCommerce.Web, :model
  use Arc.Ecto.Model


  schema "products" do
    has_many :line_items, PhoenixCommerce.LineItem
    field :name, :string
    field :description, :string
    field :price, :decimal
    field :image, PhoenixCommerce.Image.Type
    timestamps
  end

  @required_fields ~w(name description price)
  @optional_fields ~w()

  @required_file_fields ~w()
  @optional_file_fields ~w(image)

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> cast_attachments(params, @required_file_fields, @optional_file_fields)
  end
end

web/controllers/cart_controller.ex
defmodule PhoenixCommerce.CartController do
  use PhoenixCommerce.Web, :controller

  alias PhoenixCommerce.{LineItem, Cart}

  plug :add_cart

  def add_cart(conn, _opts) do
    # We look in the session to see if there's a cart uuid
    cart = case get_session(conn, :cart_uuid) do
      # If there's not one, we insert a new cart
      nil ->
        Repo.insert!(%Cart{})
      # Otherwise, we fetch the cart with that uuid from the repo
      cart_uuid ->
        query =
          from c in Cart,
          where: c.uuid == ^cart_uuid
        Repo.one(query)
    end

    # Then we'll assign the cart to the assigns map, and we'll set the uuid in
    # the session.
    conn
    |> assign(:cart, cart)
    |> put_session(:cart_uuid, cart.uuid)
  end

  def show(conn, _params) do
    query =
      from li in LineItem,
      where: li.cart_id == ^conn.assigns[:cart].id,
      preload: [:product]

    line_items = Repo.all(query)

    render conn, "show.html", %{line_items: line_items}
  end

  def add(conn, %{"product" => %{"id" => product_id}}) do
    LineItem.changeset(%LineItem{}, %{
      product_id: product_id,
      quantity: 1,
      cart_id: conn.assigns[:cart].id
    }) |> Repo.insert!

    redirect conn, to: cart_path(conn, :show)
  end
end

web/controllers/page_controller.ex
defmodule PhoenixCommerce.PageController do
  use PhoenixCommerce.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/product_controller.ex
defmodule PhoenixCommerce.ProductController do
  use PhoenixCommerce.Web, :controller

  alias PhoenixCommerce.Product

  plug :scrub_params, "product" when action in [:create, :update]

  def index(conn, _params) do
    products = Repo.all(Product)
    render(conn, "index.html", products: products)
  end

  def new(conn, _params) do
    changeset = Product.changeset(%Product{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"product" => product_params}) do
    changeset = Product.changeset(%Product{}, product_params)

    case Repo.insert(changeset) do
      {:ok, _product} ->
        conn
        |> put_flash(:info, "Product created successfully.")
        |> redirect(to: product_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    product = Repo.get!(Product, id)
    render(conn, "show.html", product: product)
  end

  def edit(conn, %{"id" => id}) do
    product = Repo.get!(Product, id)
    changeset = Product.changeset(product)
    render(conn, "edit.html", product: product, changeset: changeset)
  end

  def update(conn, %{"id" => id, "product" => product_params}) do
    product = Repo.get!(Product, id)
    changeset = Product.changeset(product, product_params)

    case Repo.update(changeset) do
      {:ok, product} ->
        conn
        |> put_flash(:info, "Product updated successfully.")
        |> redirect(to: product_path(conn, :show, product))
      {:error, changeset} ->
        render(conn, "edit.html", product: product, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    product = Repo.get!(Product, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(product)

    conn
    |> put_flash(:info, "Product deleted successfully.")
    |> redirect(to: product_path(conn, :index))
  end
end

web/views/cart_view.ex
defmodule PhoenixCommerce.CartView do
  use PhoenixCommerce.Web, :view
end

web/views/error_view.ex
defmodule PhoenixCommerce.ErrorView do
  use PhoenixCommerce.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule PhoenixCommerce.LayoutView do
  use PhoenixCommerce.Web, :view
end

web/views/page_view.ex
defmodule PhoenixCommerce.PageView do
  use PhoenixCommerce.Web, :view
end

web/views/product_view.ex
defmodule PhoenixCommerce.ProductView do
  use PhoenixCommerce.Web, :view
end

web/templates/cart/show.html.eex
<h2>Your cart</h2>
<div class="cart">
  <table>
    <thead>
      <tr>
        <td>Product</td>
        <td>Quantity</td>
      </tr>
    </thead>
    <tbody>
      <%= for line_item <- @line_items do %>
        <tr>
          <td><%= line_item.product.name %></td>
          <td><%= line_item.quantity %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello PhoenixCommerce!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="http://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

web/templates/product/edit.html.eex
<h2>Edit product</h2>

<%= render "form.html", changeset: @changeset,
                        action: product_path(@conn, :update, @product) %>

<%= link "Back", to: product_path(@conn, :index) %>

web/templates/product/form.html.eex
<%= form_for @changeset, @action, [multipart: true], fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :description, class: "control-label" %>
    <%= textarea f, :description, class: "form-control" %>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group">
    <%= label f, :price, class: "control-label" %>
    <%= number_input f, :price, step: "any", class: "form-control" %>
    <%= error_tag f, :price %>
  </div>

  <div class="form-group">
    <label>Photo</label>
    <%= file_input f, :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/product/index.html.eex
<h2>Listing products</h2>

<ul class="products">
  <%= for product <- @products do %>
    <li>
      <h3><%= link product.name, to: product_path(@conn, :show, product.id) %></h3>
      <h4>$<%= product.price %></h4>
      <img src='<%= PhoenixCommerce.Image.url({product.image, product}, :thumb) %>' />
      <p><%= product.description %></p>
    </li>
  <% end %>
</ul>

<%= link "New product", to: product_path(@conn, :new) %>

web/templates/product/new.html.eex
<h2>New product</h2>

<%= render "form.html", changeset: @changeset,
                        action: product_path(@conn, :create) %>

<%= link "Back", to: product_path(@conn, :index) %>

web/templates/product/show.html.eex
<h2>Show product</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @product.name %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @product.description %>
  </li>

  <li>
    <strong>Price:</strong>
    <%= @product.price %>
  </li>

</ul>

<%= form_for @conn, add_to_cart_path(@conn, :add), [as: "add_to_cart"], fn f -> %>
  <%= hidden_input(:product, :id, value: @product.id) %>
  <%= submit "Add to cart", class: "add-to-cart" %>
<% end %>

<%= link "Edit", to: product_path(@conn, :edit, @product) %>
<%= link "Back", to: product_path(@conn, :index) %>